### PR TITLE
feat: Add ! as command prefix in addition to an env specific command prefix

### PR DESCRIPTION
**Pull request by Alc-Alc**
[//]: # "By submitting this pull request, you agree to:"
[//]: # "- follow [PSFs's Code of Conduct](https://www.python.org/psf/conduct/)"
[//]: # "- follow [Bytes's contribution guidelines](https://github.com/JacobCoffee/byte/blob/main/CONTRIBUTING.rst)"

### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description
[//]: # "Please describe your pull request for new release changelog purposes"

- Add ! as command prefix in addition to an env specific command prefix. This enables users to do things like `!ping` and `nibble ping`

### Close Issue(s)
[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

-

### CODE REVIEW

**Review by JacobCoffee — APPROVED** [review]

**Comment by Alc-Alc** [comment]
@all-contributors add @Alc-Alc for code (just checking, I know you don't have this)

**Comment by JacobCoffee** [comment]
@all-contributors add @Alc-Alc for code

**Comment by JacobCoffee** [comment]
@all-contributors add @Alc-Alc for code

**Comment by JacobCoffee** [comment]
@all-contributors add @Alc-Alc for code, ideas

**Pull request merged**
